Add conda-recipes for DIRACOS2
DIRACGrid/management pull request #23
Opened 2020-10-21 11:45 UTC by chrisburr

Requires:
* https://github.com/DIRACGrid/tornado_m2crypto/pull/1
* https://github.com/DIRACGrid/tornado_m2crypto/pull/2
* https://github.com/DIRACGrid/tornado/pull/1

2020-10-29 07:49 UTC, chrisburr commented
@andresailer Apparently I don't have permission to assign you or request a review, but this is the first DIRACOS2-related PR for you take a look at.

In case you're not watching this repository, cc @chaen @fstagni @petricm

2020-11-04 10:17 UTC, andresailer requested changes
In the PR comment you write "I've already built these and uploaded them". 

Please clarify in the README: if a new package or version of an existing is added to these recipes, are they then automatically uploaded to the diracgrid channel, or does one have to do something manually?

2020-11-04 10:17 UTC, andresailer commented on conda-recipes/README.md
> +The `extra-packages/conda_build_config.yaml` file is a "[variant config file](https://conda.io/projects/conda-build/en/latest/resources/variants.html#creating-conda-build-variant-config-files)" which
```suggestion
The `conda-recipes/conda_build_config.yaml` file is a "[variant config file](https://conda.io/projects/conda-build/en/latest/resources/variants.html#creating-conda-build-variant-config-files)" which is used to constrain the versions of dependencies. Currently this is only used to set the Python interpreter version. If shared library dependencies are added, new values should be added based on the main [conda-forge configuration](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml).
```
?

2020-11-04 10:17 UTC, andresailer commented on conda-recipes/README.md
> +If it is absolutely essential for DIRAC to have a custom build of a package, a new directory can be added here. An reference for the `meta.yaml` syntax can be found [here](https://conda.io/projects/c
```suggestion
If it is absolutely essential for DIRAC to have a custom build of a package, a new directory can be added here. A reference for the `meta.yaml` syntax can be found [here](https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html) and the [conda-forge](https://conda-forge.org/feedstocks/) is a good source of examples. You can then test building packages by running:
```

2020-11-04 10:35 UTC, chrisburr commented
Thanks for taking a look @andresailer, I've made the changes.

For the build and upload of packages, I don't think it's worth the hassle of automating for now but if we start uploading packages frequently we can revaluate.

2020-11-04 10:37 UTC, andresailer approved these changes

2020-11-04 10:38 UTC, andresailer commented
Yes, I agree.

2020-12-03 09:53 UTC, merged